#!/usr/bin/env bash

alias dev='cd ${HOME}/code/'
alias grep='grep --color=auto'
alias vi='vim'

export EDITOR='vim'
export TERM='xterm-256color'

if command -v xdg-open >/dev/null 2>&1 && ! command -v open >/dev/null 2>&1; then
  alias open='xdg-open'
fi

bump_deps() {
  if [[ -e "package.json" ]]; then
    ncu -u
    npm install --ignore-scripts
    npm audit fix
  fi
}
