#!/usr/bin/env bash

alias dev="cd ${HOME}/Documents/dev/"
alias grep="grep --color=auto"

export EDITOR=vim
export TERM=xterm-256color

bump_deps() {
  if [[ -e "package.json" ]]; then
    ncu -u
    npm install --ignore-scripts
    npm audit fix
  fi
}
