#!/usr/bin/env bash

if ! command -v fzf >/dev/null 2>&1; then
  return
fi

if command -v git >/dev/null 2>&1; then
  grip() {
    fzf --ansi --reverse --tiebreak=index --no-sort --no-hscroll --preview 'f() { set -- $(echo -- "$@" | grep -o "[a-f0-9]\{7\}"); [ $# -eq 0 ] || git show --color=always $1; }; f {}'
  }
fi

if command -v pass >/dev/null 2>&1; then
  _fzf_complete_pass() {
    FZF_COMPLETION_TRIGGER="" _fzf_complete "-1" "${@}" < <(
      local PASS_DIR=${PASSWORD_STORE_DIR:-${HOME}/.password-store}
      find "${PASS_DIR}" -name "*.gpg" -print | sed -e "s|${PASS_DIR}/\(.*\)\.gpg$|\1|"
    )
  }
  [[ -n ${BASH} ]] && complete -F _fzf_complete_pass -o default -o bashdefault pass

  passfor() {
    if pass -c "${1}" && [[ "$(pass show "${1}" | grep -c "^otpauth:")" -eq 1 ]]; then
      read -s -r -p "  Press enter for otp"
      echo ""

      pass otp -c "${1}"
    fi
  }
  [[ -n ${BASH} ]] && complete -F _fzf_complete_pass -o default -o bashdefault passfor
fi

if command -v make >/dev/null 2>&1; then
  _fzf_complete_make() {
    # From https://unix.stackexchange.com/a/230050
    FZF_COMPLETION_TRIGGER="" _fzf_complete "-1" "${@}" < <(make -pqr 2>/dev/null | awk -F':' '/^[a-zA-Z0-9][^$#\/\t=]*:([^=]|$)/ {split($1,A,/ /);for(i in A)print A[i]}' | grep -v Makefile | sort -u)
  }
  [[ -n ${BASH} ]] && complete -F _fzf_complete_make -o default -o bashdefault make
fi

if command -v ssh >/dev/null 2>&1; then
  _fzf_complete_ssh_notrigger() {
    FZF_COMPLETION_TRIGGER="" _fzf_host_completion
  }
  [[ -n ${BASH} ]] && complete -F _fzf_complete_ssh_notrigger -o default -o bashdefault ssh
fi
