#!/usr/bin/env bash

if ! command -v git >/dev/null 2>&1; then
  return
fi

...() {
  cd "$(git_root)" || return 1
}

git_root() {
  git rev-parse --is-inside-work-tree > /dev/null 2>&1 && cd "$(git rev-parse --show-toplevel)"
}
