#!/usr/bin/env sh

function git_info() {
  git rev-parse --is-inside-work-tree &>/dev/null || return
  branch=`git symbolic-ref -q HEAD | sed -e 's|^refs/heads/||'`
  dirty=`git diff --quiet --ignore-submodules HEAD &>/dev/null; [ $? -eq 1 ] && echo -e "*"`

  echo " ("$branch$dirty")"
}

function git_prune() {
  git branch --merged | egrep -v "(^\*|master)" | xargs git branch -d
}

function git_pull() {
  git_browse 'git pull'
}
