#!/usr/bin/env bash

export GIT_PS1_SHOWDIRTYSTATE="true"
export GIT_PS1_STATESEPARATOR="|"
export GIT_PS1_SHOWSTASHSTATE="true"
export GIT_PS1_SHOWUNTRACKEDFILES="true"
export GIT_PS1_COMPRESSSPARSESTATE="true"

export PROMPT_DIRTRIM="3"

var_color() {
  export RED='\033[0;31m'
  export GREEN='\033[0;32m'
  export BLUE='\033[0;34m'
  export YELLOW='\033[33m'
  export RESET='\033[0m'
}

var_color

_previous_status() {
  if [[ ${?} -eq 0 ]]; then
    printf -- "%b✔%b" "${GREEN}" "${RESET}"
  else
    printf -- "%bx%b" "${RED}" "${RESET}"
  fi
}

PS1="${BLUE}\u${RESET}@${RED}\h${RESET} ${GREEN}\w${RESET}"
if command -v git >/dev/null 2>&1 && [[ "$(type -t __git_ps1)" == "function" ]]; then
  PS1+="${YELLOW}\$(__git_ps1)${RESET}"
fi

PS1+=" \$(_previous_status)\n> "
export PS1