#!/usr/bin/env sh

for file in ${HOME}/Documents/dev/dotfiles/sources/*; do
  [ -r "${file}" ] && [ -f "${file}" ] && source ${file}
done

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
